# Kotlinx Serialization — keep serializers generated by the compiler plugin.
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.**
-keepclassmembers class **$$serializer { *; }
-keepclasseswithmembers class com.hereliesaz.magnom.** {
    kotlinx.serialization.KSerializer serializer(...);
}
-keep,includedescriptorclasses class com.hereliesaz.magnom.**$$serializer { *; }
-keepclassmembers class com.hereliesaz.magnom.** {
    *** Companion;
}

# Koin
-keep class org.koin.** { *; }
-keepclassmembers class * { public <init>(...); }

# usb-serial-for-android reflectively loads driver classes
-keep class com.hoho.android.usbserial.driver.** { *; }

# Coroutines
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}

# Tink (via androidx.security-crypto) references compile-only annotations at runtime paths.
-dontwarn com.google.errorprone.annotations.**
-dontwarn javax.annotation.**
-dontwarn javax.annotation.concurrent.**
