package com.hereliesaz.magnom.logic

import android.media.AudioAttributes
import android.media.AudioFormat
import android.media.AudioTrack
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

/**
 * Handles audio playback for generated magnetic waveforms.
 *
 * Uses Android's [AudioTrack] API in PCM_FLOAT mode to play high-fidelity
 * square waves generated by [WaveformDataGenerator].
 */
class AudioPlayer {
    private var audioTrack: AudioTrack? = null
    private val scope = CoroutineScope(Dispatchers.IO)

    /**
     * Plays the provided waveform data.
     *
     * @param waveformData Float array representing the PCM audio (range -1.0 to 1.0).
     */
    fun play(waveformData: FloatArray) {
        scope.launch {
            val bufferSize = AudioTrack.getMinBufferSize(
                44100,
                AudioFormat.CHANNEL_OUT_MONO,
                AudioFormat.ENCODING_PCM_FLOAT
            )

            audioTrack = AudioTrack.Builder()
                .setAudioAttributes(
                    AudioAttributes.Builder()
                        .setUsage(AudioAttributes.USAGE_MEDIA)
                        .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
                        .build()
                )
                .setAudioFormat(
                    AudioFormat.Builder()
                        .setEncoding(AudioFormat.ENCODING_PCM_FLOAT)
                        .setSampleRate(44100)
                        .setChannelMask(AudioFormat.CHANNEL_OUT_MONO)
                        .build()
                )
                .setBufferSizeInBytes(bufferSize)
                .build()

            audioTrack?.let {
                it.play()
                it.write(waveformData, 0, waveformData.size, AudioTrack.WRITE_BLOCKING)
            }
        }
    }

    /**
     * Stops playback and releases resources.
     */
    fun stop() {
        audioTrack?.let {
            if (it.playState == AudioTrack.PLAYSTATE_PLAYING) {
                it.stop()
            }
            it.release()
        }
        audioTrack = null
    }
}
